"""Generate config/universe_500.yaml (M10): curated 130 + scan-ranked top-up.

Reads the latest scan snapshot from Postgres (refuses if > 7 days stale), the
first-daily-bar dates from the scan warehouse (data/scan.duckdb), sector labels
from config/sectors_500.yaml (created by scripts/enrich_sectors.py; missing
file => everything UNKNOWN), and writes config/universe_500.yaml. The output is
COMMITTED -- regeneration is reviewed via git diff, never hand-maintained.

    python scripts/build_universe_500.py [--target 500]
"""
import logging
from datetime import date

import pandas as pd
import typer
import yaml

from rs_spy.config import get_settings
from rs_spy.scan.bars import connect_scan
from rs_spy.scan.universe500 import TARGET_SIZE, build_universe_yaml, select_topup
from rs_spy.store.connection import connect_pg
from rs_spy.store.scan_repository import get_universe_snapshot
from rs_spy.universe import load_universe

app = typer.Typer()

MAX_SCAN_AGE_DAYS = 7


class StaleScanError(RuntimeError):
    """The newest scan snapshot is too old to rank liquidity from."""


def latest_scan_date(conn) -> date:
    with conn.cursor() as cur:
        cur.execute("SELECT max(scan_date) AS scan_date FROM scan_runs")
        row = cur.fetchone()
    newest = row["scan_date"] if row else None
    if newest is None or (date.today() - newest).days > MAX_SCAN_AGE_DAYS:
        raise StaleScanError(
            f"newest scan snapshot is {newest}; need one within "
            f"{MAX_SCAN_AGE_DAYS} days -- run scripts/run_nightly_scan.py first"
        )
    return newest


def first_daily_bars(con, symbols: list[str]) -> dict[str, pd.Timestamp]:
    """Earliest stored daily bar per requested symbol (scan warehouse)."""
    rows = con.execute(
        "SELECT symbol, min(ts) AS first_ts FROM bars "
        "WHERE timespan = 'day' AND symbol IN (SELECT unnest(?::VARCHAR[])) "
        "GROUP BY symbol",
        [list(symbols)],
    ).fetchall()
    return {sym: pd.Timestamp(ts) for sym, ts in rows}


@app.command()
def main(target: int = TARGET_SIZE) -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    settings = get_settings()
    curated = load_universe(settings.config_dir / "universe.yaml")

    conn = connect_pg(settings.database_url)
    try:
        scan_date = latest_scan_date(conn)
        snapshot = get_universe_snapshot(conn, scan_date)
    finally:
        conn.close()

    passing_syms = snapshot.loc[snapshot["passed"] == True, "symbol"].tolist()  # noqa: E712
    con = connect_scan(settings.resolved_scan_warehouse_path(), read_only=True)
    try:
        first_bar = first_daily_bars(con, passing_syms)
    finally:
        con.close()

    sectors_path = settings.config_dir / "sectors_500.yaml"
    sectors = (
        (yaml.safe_load(sectors_path.read_text()) or {}).get("sectors", {})
        if sectors_path.exists() else {}
    )

    topup = select_topup(snapshot, first_bar, curated.trade_symbols, target=target)
    doc = build_universe_yaml(curated, topup, sectors)

    out = settings.config_dir / "universe_500.yaml"
    header = (
        f"# GENERATED by scripts/build_universe_500.py -- do not hand-edit.\n"
        f"# scan_date={scan_date} target={target} curated={len(curated.trade_symbols)} "
        f"topup={len(topup)}\n"
    )
    out.write_text(header + yaml.safe_dump(doc, sort_keys=False))
    n_unknown = sum(1 for e in doc["universe"] if e["sector"] == "UNKNOWN")
    typer.echo(
        f"{len(doc['universe'])} symbols -> {out} "
        f"({len(topup)} top-up, {n_unknown} UNKNOWN sectors)"
    )


if __name__ == "__main__":
    app()
